version: "3"

services: 
    frontend:
        image: frontend
        stdin_open: true
        ports: 
            - "3000:3000"
        networks: 
            - red
    backend:
        image: backend
        ports: 
            - "7007:7007"
        networks: 
            - red
networks: 
    red: 
        driver: bridge